"""arrumando nome da coluna..

Revision ID: e33c2de2b182
Revises: 6fdf34d948ab
Create Date: 2026-07-31 12:04:10.555984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33c2de2b182'
down_revision: Union[str, Sequence[str], None] = '6fdf34d948ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', sa.DATETIME(), nullable=False))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
